### PR TITLE
feat: use the new timestamp markdown where possible

### PR DESCRIPTION
**Pull request by SpaceEEC**
This PR makes use of the new timestamp markdown has added where it is of use.

This markdown is not yet available on all clients (looking at you, mobile clients), so this PR has to sit here a for a bit.

### CODE REVIEW

**Comment by wizardlink** [comment]
Will review when the feature is out in stable Discord.

**Comment by wizardlink** [comment]
@SpaceEEC, is there anything you want to change, 6 months later? :^)

**Comment by SpaceEEC** [comment]
I don't think so, this should still be good to go.

**Review by wizardlink — APPROVED** [review]
lgtm 🚜

**Pull request merged**
