### PR TITLE
chore: update discordjs to v12.3.1

### PR DESCRIPTION
**Pull request by SpaceEEC**
This PR updates the discord.js to 12.3.1 in order to fully move over to use Discord's new domain. ~~Since the deadline for that is quite close.~~

### CODE REVIEW

**Review by wizardlink — APPROVED** [review]
Seems good.

**Comment by wizardlink** [comment]
Should we do another version bump for this? (patch bump)

**Comment by SpaceEEC** [comment]
We probably should, since we do that when we roll out something new.

**Comment by wizardlink** [comment]
Well, yes. My question is about whether we want to make a release just for this pull request or if we should wait further. I do not mind pushing a patch release but I need your confirmation.

**Comment by SpaceEEC** [comment]
Since the deadline is in 2 days (7th of November), I think it will be just this one PR.
See: https://discord.com/channels/613425648685547541/697138785317814292/706944540971630662 (ddevs)

---

Although, contrary to that announcement, I am not aware of any formal notices about that, so they may have postponed the requirement to use their new domain.
Not taking any chances though.

**Pull request merged**
